DROP TABLE IF EXISTS t;

CREATE TABLE t(
s VARCHAR(1000),
p VARCHAR(1000),
o VARCHAR(1000),
tv REAL
);


INSERT INTO t VALUES ('http://www.Department11.University0.edu/Course33', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course33', 0.6);
INSERT INTO t VALUES ('http://www.Department0.University0.edu/UndergraduateStudent109', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department11.University0.edu/Course45', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course45', 0.6);
INSERT INTO t VALUES ('http://www.Department0.University0.edu/UndergraduateStudent187', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department0.University0.edu/UndergraduateStudent296', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department0.University0.edu/UndergraduateStudent360', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department0.University0.edu/UndergraduateStudent376', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department0.University0.edu/UndergraduateStudent462', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department0.University0.edu/UndergraduateStudent6', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department0.University0.edu/UndergraduateStudent70', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department0.University0.edu/UndergraduateStudent79', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department0.University0.edu/FullProfessor3/Publication2', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Publication2', 0.6);
INSERT INTO t VALUES ('http://www.Department1.University0.edu/AssistantProfessor5', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department1.University0.edu/Course32', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course32', 0.6);
INSERT INTO t VALUES ('http://www.Department1.University0.edu/UndergraduateStudent172', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department1.University0.edu/UndergraduateStudent226', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department1.University0.edu/UndergraduateStudent306', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department1.University0.edu/UndergraduateStudent88', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department10.University0.edu/Course22', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course22', 0.6);
INSERT INTO t VALUES ('http://www.Department10.University0.edu/Course36', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course36', 0.6);
INSERT INTO t VALUES ('http://www.Department10.University0.edu/GraduateStudent110', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department11.University0.edu/Course3', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course3', 0.6);
INSERT INTO t VALUES ('http://www.Department11.University0.edu/Course43', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course43', 0.6);
INSERT INTO t VALUES ('http://www.Department11.University0.edu/GraduateCourse7', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'GraduateCourse7', 0.6);
INSERT INTO t VALUES ('http://www.Department11.University0.edu/GraduateStudent107', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department11.University0.edu/GraduateStudent46', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department12.University0.edu/Course27', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course27', 0.6);
INSERT INTO t VALUES ('http://www.Department12.University0.edu/Course40', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course40', 0.6);
INSERT INTO t VALUES ('http://www.Department13.University0.edu/Course13', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course13', 0.6);
INSERT INTO t VALUES ('http://www.Department13.University0.edu/Course27', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course27', 0.6);
INSERT INTO t VALUES ('http://www.Department13.University0.edu/Course40', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course40', 0.6);
INSERT INTO t VALUES ('http://www.Department13.University0.edu/GraduateStudent64', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department14.University0.edu/Course36', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course36', 0.6);
INSERT INTO t VALUES ('http://www.Department14.University0.edu/GraduateStudent53', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department14.University0.edu/UndergraduateStudent97', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department2.University0.edu/AssistantProfessor3', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department2.University0.edu/Course3', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course3', 0.6);
INSERT INTO t VALUES ('http://www.Department2.University0.edu/Course43', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course43', 0.6);
INSERT INTO t VALUES ('http://www.Department2.University0.edu/UndergraduateStudent327', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department2.University0.edu/UndergraduateStudent4', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department2.University0.edu/UndergraduateStudent43', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department2.University0.edu/UndergraduateStudent55', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department3.University0.edu/Course30', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course30', 0.6);
INSERT INTO t VALUES ('http://www.Department3.University0.edu/Course44', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course44', 0.6);
INSERT INTO t VALUES ('http://www.Department3.University0.edu/UndergraduateStudent44', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department3.University0.edu/UndergraduateStudent63', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department3.University0.edu/UndergraduateStudent82', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department3.University0.edu/FullProfessor2/Publication2', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Publication2', 0.6);
INSERT INTO t VALUES ('http://www.Department4.University0.edu/Course34', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course34', 0.6);
INSERT INTO t VALUES ('http://www.Department4.University0.edu/UndergraduateStudent200', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department4.University0.edu/UndergraduateStudent236', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department4.University0.edu/UndergraduateStudent274', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department4.University0.edu/UndergraduateStudent327', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department4.University0.edu/UndergraduateStudent46', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department4.University0.edu/UndergraduateStudent7', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department5.University0.edu/Course24', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course24', 0.6);
INSERT INTO t VALUES ('http://www.Department5.University0.edu/Course38', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course38', 0.6);
INSERT INTO t VALUES ('http://www.Department5.University0.edu/GraduateStudent19', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department5.University0.edu/UndergraduateStudent44', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department5.University0.edu/FullProfessor4/Publication2', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Publication2', 0.6);
INSERT INTO t VALUES ('http://www.Department6.University0.edu/Course44', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course44', 0.6);
INSERT INTO t VALUES ('http://www.Department6.University0.edu/UndergraduateStudent238', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department6.University0.edu/UndergraduateStudent288', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department6.University0.edu/UndergraduateStudent34', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department6.University0.edu/UndergraduateStudent38', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department6.University0.edu/UndergraduateStudent5', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department6.University0.edu/UndergraduateStudent65', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department6.University0.edu/FullProfessor3/Publication0', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Publication0', 0.6);
INSERT INTO t VALUES ('http://www.Department7.University0.edu/Course35', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course35', 0.6);
INSERT INTO t VALUES ('http://www.Department7.University0.edu/Course49', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course49', 0.6);
INSERT INTO t VALUES ('http://www.Department7.University0.edu/UndergraduateStudent256', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department7.University0.edu/UndergraduateStudent276', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department7.University0.edu/UndergraduateStudent48', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department7.University0.edu/UndergraduateStudent71', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department7.University0.edu/UndergraduateStudent75', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department7.University0.edu/UndergraduateStudent79', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department7.University0.edu/UndergraduateStudent95', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department8.University0.edu/AssistantProfessor4', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department8.University0.edu/Course16', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course16', 0.6);
INSERT INTO t VALUES ('http://www.Department8.University0.edu/Course3', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course3', 0.6);
INSERT INTO t VALUES ('http://www.Department8.University0.edu/Course43', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course43', 0.6);
INSERT INTO t VALUES ('http://www.Department8.University0.edu/GraduateStudent66', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'GraduateStudent66', 0.6);
INSERT INTO t VALUES ('http://www.Department8.University0.edu/UndergraduateStudent107', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department8.University0.edu/UndergraduateStudent41', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department8.University0.edu/UndergraduateStudent64', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department9.University0.edu/Course14', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course14', 0.6);
INSERT INTO t VALUES ('http://www.Department9.University0.edu/Course28', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name', 'Course28', 0.6);
INSERT INTO t VALUES ('http://www.Department9.University0.edu/FullProfessor4', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department9.University0.edu/UndergraduateStudent147', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department9.University0.edu/UndergraduateStudent306', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.Department9.University0.edu/UndergraduateStudent40', 'http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone', 'xxx-xxx-xxxx', 0.6);
INSERT INTO t VALUES ('http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#Dean', 'http://www.w3.org/2000/01/rdf-schema#subClassOf', '_:genid2', 0.6);
INSERT INTO t VALUES ('http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.w3.org/2002/07/owl#Ontology', 0.6);
INSERT INTO t VALUES ('http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#advisor', 'http://www.w3.org/2000/01/rdf-schema#label', 'is being advised by', 0.6);
INSERT INTO t VALUES ('http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#doctoralDegreeFrom', 'http://www.w3.org/2000/01/rdf-schema#label', 'has a doctoral degree from', 0.6);
INSERT INTO t VALUES ('http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#emailAddress', 'http://www.w3.org/2000/01/rdf-schema#label', 'can be reached at', 0.6);